name: Test

on:
  pull_request:
  push:
    ignore-tags:
      - v*

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # , ubuntu-latest
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn compile
        # yarn test
        # In package.json:
        #   "test": "run-s test:*",
        #   "test:jest": "jest",
        #   "test:types": "tsc --noEmit && tsc --project ./website --noEmit",
